//  action types de vehicles
export const FETCH_VEHICLES_START = "FETCH_VEHICLES_START";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_FAIL";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";